name: Build and Deploy
on:
  push:
    tags:
      - 'v*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # this is required to get the tag refs
          sparse-checkout: |
            src
            resources
            pom.xml
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --batch-mode --file pom.xml
      - run: mkdir staging && cp target/PaeScapeLauncher-*.jar staging/
      - run: |
          ARCHIVE_NAME=$(ls staging/*)
          echo "ARCHIVE_NAME=$ARCHIVE_NAME" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging
      - name: Create new release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.ARCHIVE_NAME }}
  discord-announce:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Let the people know
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          filename: ${{ env.ARCHIVE_NAME }}
          content: "New version of the PaeScape Launcher released!" # todo: finish
          # ${{needs.build-and-deploy.outputs.html_url}}